# Generated by Django 5.1.5 on 2025-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        
    ]
