# Generated by Django 5.1.6 on 2025-02-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zipi',
        ),
    ]
