# Generated by Django 5.1.7 on 2025-03-26 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_id_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
